### PR TITLE
liveSynth - avoid having to explicitly create synthdef

### PR DESCRIPTION
**Pull request by miguel-negrao**
The defaults passed to the sd function are only used when first sending the synthdef. For creating the synth the params var is used. The default values for the sd function can therefore be derived from params by taking their value on the first tick. This ensures they will not change further which will avoid sending the synthdef again. Only changing sdbody will cause the synthdef to be sent again to scsynth.

### CODE REVIEW

**Comment by turion** [comment]
Can you reopen, rebase onto `master` and point it onto the branch `dev_vivid`?

**Comment by miguel-negrao** [comment]
> Can you reopen, rebase onto `master` and point it onto the branch `dev_vivid`?

Sure, will do that.

**Comment by miguel-negrao** [comment]
I don't think I can reopen the pull-request, perhaps I don't have privileges ? I cherry picked the commit on top of dev-vivid, that seemed easier to do. By the way dev-vivid is not building currently, so I couldn't test the PR.

**Comment by turion** [comment]
That's probably because the target branch doesn't exist anymore. Maybe it's best when you target it towards `master` right away. Then I'll merge #77 first (and possibly cherry-pick whatever is necessary).

**Comment by miguel-negrao** [comment]
I seem to not be able to change the target either, when I click the "edit" button I don't see the target pull-down menu:

imagem

Should I open a new PR ?

**Comment by turion** [comment]
Weird. Ok, then a new PR is the right course of action.

**Comment by miguel-negrao** [comment]
New PR done.

**Pull request closed without merging**
