### PR TITLE
Dev ghc 9.4

### LINKED ISSUE #107: fails with ghc-9.4 for Stackage Nightly
```
Building library for essence-of-live-coding-0.2.6..                                                                     [308/182284]
[ 6 of 41] Compiling LiveCoding.Cell.Monad                                                                                          
                                                                                                                                    
/var/stackage/work/unpack-dir/unpacked/essence-of-live-coding-0.2.6-1d9736c86ef45ccba8284a4881f4f3c3e0269ac83cbb9904143336a7082d2684
/src/LiveCoding/Cell/Monad.hs:48:6: error:                                                                                          
    • Could not deduce (base-4.17.0.0:Data.Typeable.Internal.Typeable                                                               
                          t)                                      
        arising from a superclass required to satisfy ‘Data (t s)’,                                                                 
        arising from a type ambiguity check for                                                                                     
        the type signature for ‘hoistCellKleisliStateChange’                                                                        
      from the context: (Monad m1, Monad m2,                                                                                        
                         forall s. Data s => Data (t s))                                                                            
        bound by the type signature for:                                                                                            
                   hoistCellKleisliStateChange :: forall (m1 :: * -> *) (m2 :: * -> *)
                                                         (t :: * -> *) a1 b1 a2 b2.                                                 
                                                  (Monad m1, Monad m2,                                                              
                                                   forall s. Data s => Data (t s)) =>                                               
                                                  (forall s.                                                                        
                                                   (s -> a1 -> m1 (b1, s))                                                          
                                                   -> t s -> a2 -> m2 (b2, t s))                                                    
                                                  -> (forall s. s -> t s)                                                           
                                                  -> Cell m1 a1 b1                                                                  
                                                  -> Cell m2 a2 b2                                                                  
        at src/LiveCoding/Cell/Monad.hs:(48,6)-(53,18)                                                                              
      or from: Data s                                                                                                               
        bound by a quantified context                                                                                               
        at src/LiveCoding/Cell/Monad.hs:(48,6)-(53,18)                                                                              
    • In the ambiguity check for ‘hoistCellKleisliStateChange’                                                                      
      To defer the ambiguity check to use sites, enable AllowAmbiguousTypes                                                         
      In the type signature:                                      
        hoistCellKleisliStateChange :: (Monad m1,                                                                                   
                                        Monad m2,                                                                                   
                                        (forall s. Data s => Data (t s))) =>                                                        
                                       (forall s.                                                                                   
                                        (s -> a1 -> m1 (b1, s)) -> (t s -> a2 -> m2 (b2, t s)))
                                       -> (forall s. (s -> t s)) -> Cell m1 a1 b1 -> Cell m2 a2 b2
   |                                                              
48 |   :: (Monad m1, Monad m2, (forall s . Data s => Data (t s)))                                                                   
   |      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...         
```

ps Could I suggest using a https url for the git repo in .cabal rather than ssh?

### PR DESCRIPTION
**Pull request by turion**
Fixes #107

### CODE REVIEW

**Comment by turion** [comment]
I think this cannot work before OpenGLRaw works with text-2.0

**Comment by turion** [comment]
See https://github.com/haskell-opengl/OpenGLRaw/issues/45. Seems like that package has poor maintainership.

**Comment by ysangkok** [comment]
@turion OpenGLRaw was revised in December 2022 to allow text-2.0: https://hackage.haskell.org/package/OpenGLRaw-3.3.4.1/revisions/

It also has a [new maintainer](https://github.com/haskell-opengl/OpenGLRaw/pull/46#issuecomment-1383075366). So I think OpenGLRaw should be fine now?

**Comment by turion** [comment]
This is wild. The test suite succeeds for GHC 9.2, but fails for 9.4!

**Pull request merged**
