### PR TITLE
Set up Github Workflows

### PR DESCRIPTION
**Pull request by turion**

### CODE REVIEW

**Comment by turion** [comment]
I had a lot of extras in the Travis YML, let's see whether I can port it.

**Comment by miguel-negrao** [comment]
It would be nice to have testing working again. The example in https://github.com/actions/setup-haskell appears to be easy to setup cabal and stack. Do you want me to give it a try ?

**Comment by turion** [comment]
Yes, feel free :) thanks!

**Comment by miguel-negrao** [comment]
Hi Manuel,

I have github actions working for ghc 8.10. Is that good enough for now ?

The commit is here: https://github.com/miguel-negrao/essence-of-live-coding/commit/a8ad865aaa55b2ced49b3e43a6bbfd9c2ace09df

I've added a commit on top of that to demonstrate the cache working. On that next commit nothing changed in the dependencies, so it just builds the code which is muuch faster. Check the actions log here: https://github.com/miguel-negrao/essence-of-live-coding/commit/a8ad865aaa55b2ced49b3e43a6bbfd9c2ace09df

It has builds with both cabal and stack, and runs the tests. I made some attempts at ghc 8.6 and 8.8 and 9 and it didn't seem to build but I didn't spend more time.

If this looks good I can make a pull-request without that last test commit.

Best,
Miguel

**Comment by turion** [comment]
Closed in favour of https://github.com/turion/essence-of-live-coding/pull/91

**Pull request closed without merging**
