### PR TITLE
Support GHC 9.6

### PR DESCRIPTION
**Pull request by turion**

### CODE REVIEW

**Comment by turion** [comment]
@miguel-negrao Hi :) hope you're well!

I'm having trouble bumping the GHC version because vivid doesn't build with GHC 9.6 anymore. I can't really find a repo where vivid is developed, so I don't know whether there is any chance of getting it fixed. What do you think? If we have no chance of getting vivid fixed, I'll have to drop eolc-vivid from this repo :(

**Comment by miguel-negrao** [comment]
Hi @turion ! I'll look into it !

**Comment by miguel-negrao** [comment]
The issues is currently fixes in https://github.com/miguel-negrao/vivid . It now compiles with 9.6.5, 9.8.2 and 9.10.1. While we figure out if we can make an official release of vivid with these changes I suggest pointing to that repo for now...

**Comment by miguel-negrao** [comment]
Actually, I've now found where the git repo of vivid is (https://git.sr.ht/~amindfv/vivid) and I've made a commit against that repo which is here https://github.com/miguel-negrao/vivid/tree/dev-fix-compilation .

**Comment by turion** [comment]
Thanks a lot! However it seems that the vivid maintainer is not very active?

**Comment by turion** [comment]
> While we figure out if we can make an official release of vivid with these changes I suggest pointing to that repo for now...

You mean in a `cabal.project`? We can do that to fix the CI, but what I really want is to have a compatible version released on hackage. Because this would be necessary to re-add essence-of-live-coding to stackage, for example.

**Comment by miguel-negrao** [comment]
I've tried today a different email address. Perhaps Tom doesn't use gmail anymore...

**Comment by turion** [comment]
I deactivated the build of the vivid backend for GHC 9.6.

**Comment by miguel-negrao** [comment]
It's a pity we can't get vivid updated... :-(

**Pull request merged**
